package view.collection.trie;

import controller.TrieController;
import view.common.InteractivePanel;

/**
 * Encapsula al panel principal de la aplicacion, que contiene todos los otros
 * paneles.
 * 
 * @author Agustina
 */
public class MainPanel extends javax.swing.JPanel {
  private static final long serialVersionUID = 1L;
  private TrieView trieView;
  private TrieController controller;

  /**
   * Creates new form MainPanel
   * @param trieView una vista del trie.
   */
  public MainPanel(TrieView trieView) {
    initComponents();
    this.trieView = trieView;
    this.add(trieView, java.awt.BorderLayout.CENTER);
  }

  /**
   * Agrega un controlador
   * @param controller controlador a agregar
   */
  public void addController(TrieController controller) {
    this.controller = controller;
    this.trieView.addController(controller);
    this.mainButtonPanel.addController(controller);
  }

  /**
   * Obtiene el trieView
   * @return el trie.
   */
  public TrieView getTrieView() {
    return this.trieView;
  }

  /**
   * Obtiene el panel principal que contiene los botones
   * @return el panel principal que contiene los botones
   */
  public MainButtonPanel getMainButtonPanel() {
    return this.mainButtonPanel;
  }

  /**
   * Agrega el panel interactivo
   * @param interactivePanel el panel interactivo
   */
  public void addInteractivePanel(InteractivePanel interactivePanel) {
    this.add(interactivePanel, java.awt.BorderLayout.PAGE_END);
  }

  /**
   * Obtiene el contralador
   * @return el controlador
   */
  public TrieController getController() {
    return controller;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainButtonPanel = new view.collection.trie.MainButtonPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout(5, 5));
        add(mainButtonPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.collection.trie.MainButtonPanel mainButtonPanel;
    // End of variables declaration//GEN-END:variables

}
