package view.collection.tree;

import controller.BSTHeightBalancedController;

import java.awt.BorderLayout;

/**
 *
 * @author Exe Curia
 */
public class BSTPanel extends javax.swing.JPanel {

    private BSTHeightBalancedController controller;
    private BSTHeightBalancedView view;

    /** Creates new form BSTPanel */
    public BSTPanel(BSTHeightBalancedView view, boolean withChangeParameter) {
        initComponents();
		buttonsPanel.setWithChangeParameter(withChangeParameter);
        this.view = view;
        this.add(view, BorderLayout.CENTER);
    }

    public void addController(BSTHeightBalancedController controller) {
        this.controller = controller;
        this.view.addController(controller);
        this.buttonsPanel.addController(controller);
    }

    public BSTHeightBalancedView getView() {
        return view;
    }

    public BSTButtonsPanel getButtonsPanel() {
        return buttonsPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsPanel = new view.collection.tree.BSTButtonsPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());
        add(buttonsPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        view.componentResized(evt);
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.collection.tree.BSTButtonsPanel buttonsPanel;
    // End of variables declaration//GEN-END:variables

}
