package view.structures.stacks;

import controllers.StackController;
import java.awt.BorderLayout;

/**
 *
 * @author pgorin
 */
public class StackPanel extends javax.swing.JPanel {

    private StackController controller;
    private StackView view;

    public StackPanel(StackView view) {
        initComponents();
        this.view = view;
        this.add(view, BorderLayout.CENTER);
    }

    public void addController(StackController controller) {
        this.controller = controller;
        this.view.addController(controller);
        this.buttonsPanel.addController(controller);
    }

    public StackView getView() {
        return view;
    }

    public StackButtonsPanel getButtonsPanel() {
        return buttonsPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsPanel = new view.structures.stacks.StackButtonsPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());
        add(buttonsPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.structures.stacks.StackButtonsPanel buttonsPanel;
    // End of variables declaration//GEN-END:variables

}
