package view.collection.queue;

import controller.QueueController;

/**
 *
 */
public class QueuePanel<T> extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	
	private QueueView<T> view;

    public QueuePanel(QueueView<T> view) {
    	this.view = view;
    	//this.view.setBorder(BorderFactory.createLoweredBevelBorder());
        initComponents();
    }

    public void addController(QueueController<Integer> controller) {
        this.view.addController(controller);
        this.buttonsPanel.addController(controller);
    }

    public QueueView<T> getView() {
        return view;
    }

    public QueueButtonsPanel getButtonsPanel() {
        return buttonsPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonsPanel = new QueueButtonsPanel();
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(view)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(view))
        );
//        //setBackground(new java.awt.Color(255, 255, 255));

//        this.add(buttonsPanel, BorderLayout.NORTH);
//        this.add(view);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private QueueButtonsPanel buttonsPanel;
    // End of variables declaration//GEN-END:variables
}
